### ISSUE TITLE
Plugin Needs an Update for the latest HDT Version

### ISSUE THREAD

**Issue by SwaguarTV** [CLJunge/Spawn.HDT.DeckCodeBot#1]
[From the latest HDT changelog:](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/CHANGELOG.md)
> ## **Release v1.11.2 - 2020-04-27**
> - This version updates several dependencies, causing some Plugins to no longer load.

This plugin has been an incredibly useful for my stream, could you update the plugin so it works with the latest version?
**\- SwaguarTV** ❤️

**Comment by CLJunge** [comment]
I'll look into it!

**Comment by CLJunge** [comment]
[Updated the plugin](https://github.com/CLJunge/Spawn.HDT.DeckCodeBot/releases/download/v1.0.1/Spawn.HDT.DeckCodeBot.zip) to HDT v1.10.8

**Comment by CLJunge** [comment]
I just noticed that you're talking about a future version, I'll update the plugin whenever the new version gets released.

**Comment by CLJunge** [comment]
Released the updated version.
